services:
    reforger:
        build:
            context: .
        image: mercenary9312/trainwreck-reforger-server
        container_name: reforger
        ports:
            - "2001:2001/udp"
            - "17777:17777/udp"
            - "19999:19999/udp"
        volumes:
            - ./configs:/configs
            - ./game:/profile